### ISSUE TITLE
to_s

### ISSUE THREAD

**Issue by nkpoid** [minerva1129/gaijibot#1]
to_sが散見されるが、あのメソッドたちの返り値はStringだった気がするし、そもそもrubyは往々にしていい感じにエイっと型変換をしてくれる PR打つほどでもないので、issueで

**Comment by MinervaP** [comment]
あ、そうなんだ、型ビビリ言語ばっかり書いてきたから型にびびってた、確かAddressable::URIとかいうので返ってきたはずなんだけど

**Comment by nkpoid** [comment]
もうfix済みっぽいけど,to_json時to_sが内部でかかるので明示変換する必要はないよ

**Comment by MinervaP** [comment]
なるほどね、そういえば話し変わるんだけどさ、to_strって見たんだけどto_sと違いは何

**Comment by nkpoid** [comment]
http://qiita.com/tbpgr/items/19b42765a7b9cb292f44
こことかわかりやすいと思う
